export const LOAD_PROFILE = 'app/ProfilePage/LOAD_PROFILE';
export const LOAD_PROFILE_SUCCESS = 'app/ProfilePage/LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'app/ProfilePage/LOAD_PROFILE_ERROR';
export const UPDATE_PROFILE_EDIT_MODAL_IS_OPEN =
  'app/ProfilePage/UPDATE_PROFILE_EDIT_MODAL_IS_OPEN';
export const EDIT_PROFILE = 'app/ProfilePage/EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'app/ProfilePage/EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_ERROR = 'app/ProfilePage/EDIT_PROFILE_ERROR';
export const UPDATE_PROFILE_EDIT_MODAL_FORM_GENERAL =
  'app/ProfilePage/UPDATE_PROFILE_EDIT_MODAL_FORM_GENERAL';
export const UPDATE_PROFILE_EDIT_MODAL_FORM_LOCATION =
  'app/ProfilePage/UPDATE_PROFILE_EDIT_MODAL_FORM_LOCATION';
export const LOAD_PROFILE_EDIT_MODAL_IMAGES =
  'app/ProfilePage/LOAD_PROFILE_EDIT_MODAL_IMAGES';
export const UPDATE_PROFILE_EDIT_MODAL_IMAGES_LOADED =
  'app/ProfilePage/UPDATE_PROFILE_EDIT_MODAL_IMAGES_LOADED';
export const LOAD_PROFILE_EDIT_MODAL_PROFILE_IMAGE =
  'app/ProfilePage/LOAD_PROFILE_EDIT_MODAL_PROFILE_IMAGE';
export const UPDATE_PROFILE_EDIT_MODAL_PROFILE_IMAGE_LOADED =
  'app/ProfilePage/UPDATE_PROFILE_EDIT_MODAL_PROFILE_IMAGE_LOADED';
